# Generated by Django 3.0.5 on 2021-01-12 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('authorId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blogId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=128)),
                ('description', models.TextField(default=None)),
                ('authorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Author')),
            ],
        ),
    ]
