# Generated by Django 3.0.5 on 2021-01-10 17:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blogId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=128)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', ckeditor.fields.RichTextField(default=None)),
                ('author', models.CharField(default='Mohit', max_length=128)),
                ('createdAt', models.DateTimeField()),
                ('Category One', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('Category Two', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('Category Three', models.CharField(blank=True, default=None, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=250)),
            ],
        ),
    ]
