# Generated by Django 3.1.5 on 2021-01-09 14:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('blogId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=128)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('discription', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('author', models.CharField(max_length=128)),
                ('createdAt', models.DateTimeField()),
                ('category', models.ManyToManyField(to='blogs.Category')),
            ],
        ),
    ]
