# Generated by Django 3.0.5 on 2021-01-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Category One',
            field=models.CharField(blank=True, default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Category Three',
            field=models.CharField(blank=True, default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Category Two',
            field=models.CharField(blank=True, default=None, max_length=128),
        ),
    ]
